spring:
  threads:
    virtual:
      enabled: false
  main:
    keep-alive: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springdoc: OFF

server:
  port: 20000
